name: Run Tournament
on:
  push:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.5'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - uses: actions/setup-haskell@v1.1
      - run: bash ./build.sh
      - run: ./battlebots